### ISSUE TITLE
Can specify file location

### ISSUE THREAD

**Issue by darrencomeau** [VulcanAnalytics/pickles#3]
### Feature: File Location
**In order** to control where the document is created
**As a** document reader
**I want** a to be able to specify an output folder for the document

#### Scenario: Output is written to specified location
> **Given** I specify the output folder as 'C:\testing'
> **When** I generate Markdown output
> **Then** the file 'C:\testing\features.md' exists

**Comment by darrencomeau** [comment]
@dirkrombauts please could you confirm if this is the correct behaviour?

**Comment by darrencomeau** [comment]
For the folder does not exist requirement, I note that `runner.cs` creates the folder and as such it should always exist.

Therefor if the document builder doesn't find the folder it is an error condition and I don't believe I should try to create the folder. Does that sound right?

**Comment by dirkrombauts** [comment]
It does sound right, but I would compare how/if the HTML  output builder deals with this scenario.

I’ll be out of touch until Sunday, I take part in a seminar in the middle of nowhere.

**Comment by darrencomeau** [comment]
Thanks, I'll look into the HTML builder.

I hope you enjoy your seminar.

**Comment by darrencomeau** [comment]
The `MockFileSystem` always builds the folder which makes this tricky to test.

As this is an edge case, given that `runner.cs` creates the folder, I'm going to leave that scenario out.

Pushed commit.
